print("Ejemplo de barra inclinada", "probando")
print("Ejemplo de barra inclinada\n", "probando")
print("Ejemplo de barra inclinada\\", "probando")
print("Ejemplo de barra inclinada ", end="\n")
print("aparte")
print("Ejemplo de barra inclinada ", "a", "b", sep="***")
print("aparte"*2)
print(-4 + 4) 
print(-4. + 8)
print(9 % 6 % 2)
print(9*2%4)  #Primero multiplica y despues saca el modulo
